### ISSUE TITLE
setup overleaf for final report

### ISSUE THREAD

**Issue by Humorloos** [Humorloos/web_mining#48]

**Comment by HarithF** [comment]
Link for final report https://www.overleaf.com/1875924646yqgnfpybdtmd

 Outline for project summaries provided by Prof.:
1. Introduction: problem/task formulation, research questions and objective
2. Methodology: describe the methods that you used and why you choose them
3. Experimental setting: structure and statistics of the data set, evaluation measures
4. Evaluation and discussion of the results: How do your results compare to existing solution?
5. Conclusions (what can we learn from your work?) and future direction (what would you do 
differently, or additionally, why?)
